config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "residential", to: "residentials#index"
  get "marine", to: "marines#index"
  get "commercial", to: "commercials#index"
end

app/models/ahtresidential.rb
class Ahtresidential < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commercials_controller.rb
class CommercialsController < ApplicationController
  def index
  end
end

app/controllers/marines_controller.rb
class MarinesController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/residentials_controller.rb
class ResidentialsController < ApplicationController
  def index
  end
end

app/helpers/ahts_residential_helper.rb
module AhtsResidentialHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commercials_helper.rb
module CommercialsHelper
end

app/helpers/marine_helper.rb
module MarineHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/residentials_helper.rb
module ResidentialsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/commercials/index.html.erb
<h1>Welcome to AHTcommercial</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AHTGlobal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marines/index.html.erb
<h1>Welcome to AHTmarine</h1>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>



<%= link_to "AHTresidencial", residential_path %>
<%= link_to "AHTmarine", marine_path %>
<%= link_to "AHTcommercial", commercial_path %>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/residentials/index.html.erb
<h1>Welcome to AHTresidential</h1>